const posts=[
{id:1,user:"Mika Lenz",handle:"mika.macht",avatar:"M",style:"sun",time:"vor 4 Min.",title:"Die Stadt klingt weicher, wenn's regnet.",tone:"sand",seed:11,caption:"An der Haltestelle, kurz bevor alles nach nassem Asphalt riecht. ☂️ #stadtgeräusche",likes:18,replies:12,chain:"letzte Bahn nach Hause"},
{id:2,user:"Juno Park",handle:"junobeats",avatar:"J",style:"blue",time:"vor 11 Min.",title:"Küchenlicht um zwei Uhr nachts.",tone:"blue",seed:27,caption:"Ein Kühlschrank-Brummen, ein viel zu später Tee. Mehr braucht's manchmal nicht.",likes:31,replies:8,chain:"Küchenlicht um zwei"},
{id:3,user:"Levi Noor",handle:"levi.noor",avatar:"L",style:"lilac",time:"vor 19 Min.",title:"Papa pfeift immer denselben Takt.",tone:"pink",seed:43,caption:"Heute hab ich's zum ersten Mal mitgesummt. Irgendwie war er dann kurz wieder hier.",likes:46,replies:5,chain:"Familienmelodien"},
{id:4,user:"Amara Sol",handle:"amarasound",avatar:"A",style:"coral",time:"vor 31 Min.",title:"Wenn der Bass vom Nachbarzimmer durch die Wand kommt.",tone:"lime",seed:8,caption:"Wir kennen uns nicht. Aber seit drei Wochen haben wir denselben Feierabend-Soundtrack. #dünnewände",likes:24,replies:0,chain:""},
{id:5,user:"Nika Weiss",handle:"nikasings",avatar:"N",style:"lilac",time:"vor 43 Min.",title:"Wind in den Drähten auf dem Feldweg.",tone:"lilac",seed:39,caption:"Klingt ein bisschen, als würde irgendwo jemand ganz leise antworten.",likes:13,replies:6,chain:"was der Wind noch weiß"}];
let filter="all",mood="warm",audio;const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function bars(seed,n){let x=seed>>>0;let out="";for(let i=0;i<n;i++){x=(x*1664525+1013904223)>>>0;let h=7+(x/4294967296)*20+Math.abs(Math.sin(i*.29+seed)*Math.cos(i*.095+seed*.7))*13;out+='<i class="wave-bar" style="height:'+Math.round(h)+'px;--i:'+i+'"></i>'}return out}
function draw(){let shown=posts.filter(p=>filter==="all"||(filter==="ketten"&&p.chain)||(filter==="following"&&["Mika Lenz","Juno Park","Amara Sol"].includes(p.user)));$("#postList").innerHTML=shown.map(p=>'<article class="post-card" data-id="'+p.id+'"><header class="post-header"><span class="avatar avatar-'+p.style+'">'+esc(p.avatar)+'</span><span class="post-author"><b>'+esc(p.user)+'</b><small>@'+esc(p.handle)+'</small></span><span class="post-time">'+p.time+'</span><button class="post-menu">···</button></header><h2 class="post-title">'+esc(p.title)+'</h2><div class="sound-card sound-'+p.tone+'" data-seed="'+p.seed+'" role="button" tabindex="0"><button class="sound-play">▶</button><div class="sound-wave">'+bars(p.seed,64)+'</div><div class="sound-meta">KLANGPOSTKARTE <span>0:12</span></div></div><p class="post-caption">'+esc(p.caption)+'</p><div class="post-actions"><button class="action-button like-button"><span class="action-symbol">'+(p.liked?"♥":"♡")+'</span><span class="like-count">'+p.likes+'</span></button><button class="action-button echo-button"><span class="action-symbol">⟲</span><span>'+p.replies+' Echos</span></button><button class="action-button save-button"><span class="action-symbol">⌑</span></button></div>'+(p.chain?'<div class="chain-hint"><span class="chain-link">⟲</span><span>Teil der Kette <b>„'+esc(p.chain)+'“</b></span><span class="chain-n">'+p.replies+' ECHOS</span></div>':"")+'</article>').join("")}
function notice(text){let t=$("#toast");t.textContent=text;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2100)}
function play(seed,card){audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume();$$('.sound-card.is-playing').forEach(c=>c.classList.remove("is-playing"));if(card)card.classList.add("is-playing");let now=audio.currentTime,f=150+seed*37%210;[1,1.5,2,3].forEach((r,i)=>{let o=audio.createOscillator(),g=audio.createGain();o.type=i%2?"sine":"triangle";o.frequency.value=f*r;g.gain.setValueAtTime(i===0?.024:.008,now);g.gain.exponentialRampToValueAtTime(.0001,now+2.4);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+2.5)});if(card)setTimeout(()=>card.classList.remove("is-playing"),2500)}
function open(){$("#composerBackdrop").hidden=false;document.body.style.overflow="hidden";setTimeout(()=>$("#postText").focus(),50)}function close(){$("#composerBackdrop").hidden=true;document.body.style.overflow=""}
$("#postList").addEventListener("click",e=>{let card=e.target.closest(".post-card");if(!card)return;let p=posts.find(x=>x.id===Number(card.dataset.id));if(e.target.closest(".like-button")){p.liked=!p.liked;p.likes+=p.liked?1:-1;draw()}else if(e.target.closest(".echo-button")){p.replies++;draw();open();$("#postText").value="Echo: "+p.title}else if(e.target.closest(".save-button")){let b=e.target.closest(".save-button");b.classList.toggle("liked");b.querySelector(".action-symbol").textContent=b.classList.contains("liked")?"◆":"⌑";notice("Für später gespeichert.")}else{let s=e.target.closest(".sound-card");if(s)play(+s.dataset.seed,s)}});
$("#postList").addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.matches(".sound-card")){e.preventDefault();play(+e.target.dataset.seed,e.target)}});
$$('.filter').forEach(b=>b.addEventListener("click",()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle("active",x===b));draw()}));
$$('[data-view]').forEach(b=>b.addEventListener("click",e=>{e.preventDefault();if(b.dataset.view==="ketten")$$('.filter').find(x=>x.dataset.filter==="ketten").click();else if(b.dataset.view==="feed")$$('.filter').find(x=>x.dataset.filter==="all").click();else notice("Dein Hörraum, dein Profil.");$$('[data-view]').forEach(x=>x.classList.toggle("active",x===b))}));
$("#openComposer").addEventListener("click",open);$("#mobileCompose").addEventListener("click",open);$("#closeComposer").addEventListener("click",close);$("#composerBackdrop").addEventListener("click",e=>{if(e.target.id==="composerBackdrop")close()});document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});
$$('.mood-chip').forEach(b=>b.addEventListener("click",()=>{$$('.mood-chip').forEach(x=>x.classList.toggle("chosen",x===b));mood=b.dataset.mood;$(".sound-preview").style.background={warm:"#e5d1b5",ruhig:"#b9ceca",hell:"#d8e1ae",nacht:"#d0bfd4"}[mood]}));
$("#publishPost").addEventListener("click",()=>{let input=$("#postText"),text=input.value.trim();if(!text){input.focus();return}posts.unshift({id:Date.now(),user:"Sam",handle:"sam",avatar:"S",style:"me",time:"gerade eben",title:text,tone:{warm:"sand",ruhig:"blue",hell:"lime",nacht:"lilac"}[mood],seed:Math.ceil(Math.random()*50),caption:"Ein neuer Moment von dir. Wer hört, darf weiterklingen.",likes:0,replies:0,chain:text});filter="all";$$('.filter').forEach(x=>x.classList.toggle("active",x.dataset.filter==="all"));draw();close();input.value="";notice("Deine Klangkette ist jetzt im Hörraum.");window.scrollTo({top:0,behavior:"smooth"})});
$("#previewWave").innerHTML=bars(19,38);$$('#previewWave i').forEach(i=>i.style.height=Math.max(5,parseInt(i.style.height)*.55)+"px");$("#previewPlay").addEventListener("click",e=>{play(19);e.currentTarget.textContent="Ⅱ";setTimeout(()=>e.currentTarget.textContent="▶",1700)});$("#promptReply").addEventListener("click",()=>{open();$("#postText").value="Ein sicherer Ort klingt wie …"});$("#seeAllChains").addEventListener("click",()=>$$('.filter').find(x=>x.dataset.filter==="ketten").click());$$('.chain-item').forEach(b=>b.addEventListener("click",()=>{$$('.filter').find(x=>x.dataset.filter==="ketten").click();notice('Klangkette „'+b.querySelector("b").textContent+'“ geöffnet.')}));$("#inviteButton").addEventListener("click",()=>notice("Teile nebenklang mit jemandem, der Musik fühlt."));$$('.equalizer i').forEach((i,n)=>{i.style.setProperty("--h",5+Math.abs(Math.sin(n*.68))*17+"px");i.style.setProperty("--i",n)});draw();